### ISSUE TITLE
Docker build action fails

### ISSUE THREAD

**Issue by jishminor** [smarter-project/smarter-inference#3]
It seems that sourcing the base image from ghcr.io is failing. I notice that the Docker login step is logging in as my user. Not sure if this is the behavior we want or not.

**Comment by ericvh** [comment]
it shouldn't be private....so you shouldn't even have to login - or are you talking about update?  Which image were you trying to source - did you upload a triton one?  You might need to make it public (sometimes they default to private)

**Comment by ericvh** [comment]
confirmed, when you created it you accidentally made it private (which might have been the default, I fixed this manually.  Just go make sure there isn't a private next to the package next time -- you can go into the package and click settings -> advanced -> change visibility to fix.
